name: Build and Test

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        working-directory: C++Programs/mini-redis
        run: cmake -S . -B build

      - name: Build project
        working-directory: C++Programs/mini-redis
        run: cmake --build build

      - name: Run tests
        working-directory: C++Programs/mini-redis
        run: ctest --tests-dir build --output-on-failure
